export type OWGameEvent = overwolf.gep.ApexLegends.GameEvent;
export type OWGameEventKillFeed = overwolf.gep.ApexLegends.GameEventKillFeed;
// export type OWGameInfoUpdatedEvent = overwolf.games.GameInfoUpdatedEvent;
export type OWInfoUpdates2Event = overwolf.gep.ApexLegends.InfoUpdates2Event; // overwolf.games.events.InfoUpdates2Event
export type OWMatchInfo = overwolf.gep.ApexLegends.MatchInfo;
export type OWMatchInfoMe = overwolf.gep.ApexLegends.MatchInfoMe;
export type OWMatchInfoMeInventory = overwolf.gep.ApexLegends.MatchInfoMeInventory;
export type OWMatchInfoMeWeapons = overwolf.gep.ApexLegends.MatchInfoMeWeapons;
export type OWMatchInfoRoster = overwolf.gep.ApexLegends.MatchInfoRoster;
export type OWNewGameEvents = overwolf.gep.ApexLegends.NewGameEvents; // overwolf.games.events.NewGameEvents
export type OWRunningGameInfo = overwolf.games.RunningGameInfo;
