// export type OWGameInfoUpdatedEvent = overwolf.games.GameInfoUpdatedEvent;
export type OWGameEvent = overwolf.gep.ApexLegends.GameEvent;
export type OWGameEventKillFeed = overwolf.gep.ApexLegends.GameEventKillFeed;
export type OWHotKey = overwolf.settings.hotkeys.IHotkey;
export type OWHotKeyAssignHotkeyObject = overwolf.settings.hotkeys.AssignHotkeyObject;
export type OWHotKeyGetAssignedHotkeyResult = overwolf.settings.hotkeys.GetAssignedHotkeyResult;
export type OWHotKeyOnPressedEvent = overwolf.settings.hotkeys.OnPressedEvent;
export type OWHotKeyUnassignHotkeyObject = overwolf.settings.hotkeys.UnassignHotkeyObject;
export type OWInfoUpdates2Event = overwolf.gep.ApexLegends.InfoUpdates2Event; // overwolf.games.events.InfoUpdates2Event
export type OWMatchInfo = overwolf.gep.ApexLegends.MatchInfo;
export type OWMatchInfoLegendSelect = overwolf.gep.ApexLegends.MatchInfoLegendSelect;
export type OWMatchInfoMe = overwolf.gep.ApexLegends.MatchInfoMe;
export type OWMatchInfoMeInventory = overwolf.gep.ApexLegends.MatchInfoMeInventory;
export type OWMatchInfoMeWeapons = overwolf.gep.ApexLegends.MatchInfoMeWeapons;
export type OWMatchInfoRoster = overwolf.gep.ApexLegends.MatchInfoRoster;
export type OWMatchInfoTeammate = overwolf.gep.ApexLegends.MatchInfoTeammate;
export type OWMouseEvent = overwolf.games.inputTracking.MouseEvent;
export type OWNewGameEvents = overwolf.gep.ApexLegends.NewGameEvents; // overwolf.games.events.NewGameEvents
export type OWRunningGameInfo = overwolf.games.RunningGameInfo;
export type OWStopStreamingEvent = overwolf.streaming.StopStreamingEvent;
export type OWStopStreamingResult = overwolf.streaming.StopStreamingResult;
export type OWStreamEvent = overwolf.streaming.StreamEvent;
export type OWStreamResult = overwolf.streaming.StreamResult;
export type OWStreamSettings = overwolf.streaming.StreamSettings;
export type OWSystemTrayMenuItem = overwolf.os.tray.menu_item;
export type OWVideoSplitedEvent = overwolf.streaming.VideoFileSplitedEvent;
