export interface AimingReticle {
    reticleId: string;
    friendlyName: string;
    filename: string;
    hexColor: string;
    sizePercent: number;
    alpha: number;
}

export const AimingReticleList: AimingReticle[] = [
    {
        reticleId: "dotsmall",
        friendlyName: "Dot Small",
        filename: "dot.svg",
        hexColor: "#ffffff",
        sizePercent: 0.015,
        alpha: 0.75,
    },
    {
        reticleId: "dotmedium",
        friendlyName: "Dot Medium",
        filename: "dot.svg",
        hexColor: "#ffffff",
        sizePercent: 0.03,
        alpha: 0.75,
    },
    {
        reticleId: "dotlarge",
        friendlyName: "Dot Large",
        filename: "dot.svg",
        hexColor: "#ffffff",
        sizePercent: 0.05,
        alpha: 0.75,
    },
    {
        reticleId: "circledash",
        friendlyName: "Circle Dash",
        filename: "circle-dash.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "circledashcross",
        friendlyName: "Circle Dash Cross",
        filename: "circle-dash-cross.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "circlehalfhorizontal",
        friendlyName: "Circle Half Horizontal",
        filename: "circle-half-horizontal.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "circlehalfvertical",
        friendlyName: "Circle Half Vertical",
        filename: "circle-half-vertical.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "circlelarge",
        friendlyName: "Circle Large",
        filename: "circle-large.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "circlelargethin",
        friendlyName: "Circle Large Thin",
        filename: "circle-large-thin.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "circlemedium",
        friendlyName: "Circle Medium",
        filename: "circle-medium.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "circlemediumthin",
        friendlyName: "Circle Medium Thin",
        filename: "circle-medium-thin.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "circlesmall",
        friendlyName: "Circle Small",
        filename: "circle-small.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "circlesmallthin",
        friendlyName: "Circle Small Thin",
        filename: "circle-small-thin.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "crossdash",
        friendlyName: "Cross Dash",
        filename: "cross-dash.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "crossnail",
        friendlyName: "Cross Nail",
        filename: "cross-nail.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "horizontaldash",
        friendlyName: "Horizontal Dash",
        filename: "horizontal-dash.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "horizontaltube",
        friendlyName: "Horizontal Tube",
        filename: "horizontal-tube.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "plusdash",
        friendlyName: "Plus Dash",
        filename: "plus-dash.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "plusnail",
        friendlyName: "Plus Nail",
        filename: "plus-nail.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "square",
        friendlyName: "Square",
        filename: "square.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "squaredash",
        friendlyName: "Square Dash",
        filename: "square-dash.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "squareedge",
        friendlyName: "Square Edge",
        filename: "square-edge.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "tri",
        friendlyName: "Tri",
        filename: "tri.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "tridown",
        friendlyName: "Tri Down",
        filename: "tri-down.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "trinarrow",
        friendlyName: "Tri Narrow",
        filename: "tri-narrow.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "verticaldash",
        friendlyName: "Vertical Dash",
        filename: "vertical-dash.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
    {
        reticleId: "verticaltube",
        friendlyName: "Vertical Tube",
        filename: "vertical-tube.svg",
        hexColor: "#ffffff",
        sizePercent: 0.3,
        alpha: 0.75,
    },
];
